# This file was generated by GoReleaser. DO NOT EDIT.
cask "steer" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "60f924f6423f2c56758a379e7bc2cd440015ddde263fd9230a5d0882a0559960"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eda74e2bfd67f91e85fa9f62ddaf58e3bc403a09f623aa3dc77b685a3a794ea3"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cfa30de9a41cceed7fafa507c4472e533d912d8afaba5a828a2f2ff5f9e32845"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93a4ac79499f39fdfbfa937c27190631b5393ffc22df9007d4f058525490ee06"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "steer"
  desc "The simplicity of a PaaS, on your own AWS — deploy, scale and watch services from CLI/TUI"
  homepage "https://github.com/juanMaAV92/steer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/steer"]
    end
  end

  # No zap stanza required

end
