# This file was generated by GoReleaser. DO NOT EDIT.
cask "steer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "943c34dcf3268803a10b5a713e510036e5f79d67766b0c0616d2de9490c31587"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c768e8d7b60c3dd47f32d54e6fad642e951de5221d6247ba68fc64c906cd267"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6be321d2bb9a78a36104508f3fac3b82e9059dc100357e33d6c92ddef7fc8dda"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72dc25f630da45aa0146cd8d33d811d9a8fff6287f7df7fe7be27ea0e05f8d73"
      url "https://github.com/juanMaAV92/steer/releases/download/v#{version}/steer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "steer"
  desc "The simplicity of a PaaS, on your own AWS — deploy, scale and watch services from CLI/TUI"
  homepage "https://github.com/juanMaAV92/steer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "steer"

  # No zap stanza required

end
